---
title: "Group Project 2"
subtitle: "Biology 368/664 Bucknell University"
output: html_notebook
author: Matt & Jordan
date: 19 Feb 2019
---

## Objectives

1. Critically read a scientific paper and assess the evidence provided
2. Assess a published paper for issues with reproducibility and transparency
3. Identify questionable research practices and describe appropriate methods to prevent them
4. Complete a preregistration plan describing a confirmatory study following the principles of 


- Read and discuss your paper with your group partner
  + Focus on the methods and results
  + For each conclusion evaluate the strength of the supporting evidence
KF: Good summary of your concerns with the analysis
  
  Initial Thoughts:
  Figure 4 potentially not showing what the authors think it does/overstretching results (basically a mess)
  Figure 2 b, c, d: confusing on what they're trying to do here, put groups together based upon what gave them the best results. "n" is all over the place (ex: 15, 123.) Neutral and aggressive groups are combined for statisical power? Strong evidence for p hacking. Chose to do generation 11 (but why? Is there data/previous studies showing generation 11 is significant?) 
  Figure 3: pretty significant data shown, non-confusing way (good figure)
  They also bounce back and forth between different generations (ie, table 2 only reporting )
  In the statisical analysis, they said none of their data was normal/normally distributed, most of the aggression data is not normally distributed. Researchers ran normality tests and multiple comparison tests post-hoc.
  Log transformed data, divided by median value
  Figure 3: no mention of whether there is food present or not, which could impact aggressive and territorial behavior. Measured in escalations per hour, and given an average. Authors mentioned that escalations continued throughout the day, as it was measured for six hours.
  
  
  
  
- Complete the nr-reporting-summary.pdf checklist (open in Adobe Acrobat)
  + For any deficient items on the checklist, describe the information needed
  + Refer to nr-reporting-life-sciences-research.pdf for guidelines
  
  Done - see updated document
KF: Good work on this document. How do you think the lack of blinding could affect the results? 
Were there subjective measurements made that could be influenced by observer bias?  

  The lack of blinding could have allowed them to screen for flies that showed aggressive behaviour, but were not truly aggressive because of a genetic predisposition. The process of screening flies from the video footage was subjective. It is possible that one researcher could have determined a specified behavior was aggressive, but that someone else would not agree with that determination. Given that the flies are so small as well and the video footage was 30 minutes long, it is possible that they could have missed some demonstrations of aggressive behavior. 
  
  
- Determine if you could repeat the analysis that is most essential to conclusions of the paper
  + If data or methods are not available, look for follow-up studies that provide the required details
  -We could probably do everything they mentioned in R, we would just need the data they used. Their methods are listed and analysis is pretty straight forward in regards to what tests were used. We were able to obtain their raw data, but the data file is only available in HTML and reading it into R might be difficult. Data is actually in text file, and two other files that are probably not compatiable with R. 
KF: I bet there is a package for that!  
  
    There is a package called XML that we can use in R to analyze text files. The text file could also be analyzed relatively easily. The problem with the file is that it was provided in the form of a matrix. They did not supply an information about the data in the matrix, so it is impossible to tell what exactly the data in that matrix means. As a result, it would be difficult to reproduce anything that would have a meaningful outcome.
  
  
- For each Questionable Research Practice discussed in Fraser *et al*:
  + Find evidence to exclude this QRP, or
  + Describe steps that should have been taken to prevent this QRP (see Forstmeier *et al*)
KF: Nice concise summary.
  
  Cherry-picking:
  In table 2, they only list genes that are statisically significant, no mention of supplementary table 2 in which non statiscally significant genes would be reported
  
  HARKing:
  HARKing is basically outlined in the discussion, they said their selection process became more stringent as the flies became more aggressive but this would be an unexpected finding and they did not denote that this was unexpected. Could avoid HARKing with the pre-reg document.
  
  P-hacking:
  We found evidence of this in figure 2, strange grouping to obtain statistical significance (grouping aggressive and neutral flies together)
  Could be avoided via not grouping them together, providing a proper and even "n"
  
  
  
  
- Design a follow-up study to replicate the most crucial experiment
  + Complete the PreregChallengeTemplate.Rmd form for this replication experiment
KF: Good work on this. How could you blind the experimenter to the fly group when they were evaluating the behavior?

    You could blind the experimenter when they evaluate the fly group by randomly assigning the flies to different groups (no prior determination of their genetic predisposition to agressiveness), then ask the researcher to monitor behaviour. This way, the researcher does not expect to see aggresive behavior in a group. What I would do is create a homogenous population of flies of all type. Then I would split them into random groups and examine their behavior within the random groups. While I monitor the flies, I would screen them for aggressiveness and then removed those that display aggressive behaviour. I would then examine the "non-aggressive" (not removed from initial population) and aggressive flies separately and compare the level of aggression between the groups. Doing so would confirm the flies I removed were aggressive because of their inate behavior rather than from than by chance that they demonstrated it in the initial screening. Continuing the analysis after just one screening would cause me to operate under the assumption that aggression could have been caused by chance rather than by some underlying variable.
  
  Most crucial experiment: Figure 3: Aggression quantification in poulation cage at Gen22 and Aggr-Neutr mixed populations and pairs. Basically shows that aggressive flies are more aggressive than neutral flies.
  
  
- Present summary of reproducibility assessment in class





Additional credit will be awarded for providing assistance to other groups and for completion of the analysis that supports the most essential conclusion.

**Acknowledgements**

Initial project work was done together (both Matt and Jordan). After draft comments, we split the work by Matt working on the suggestions made by Prof Field and Jordan working on the reproducibility aspect. 
